# Generated by Django 5.0 on 2023-12-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'ContactUs'},
        ),
    ]
