# Generated by Django 5.0 on 2023-12-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ContactUs', 'verbose_name_plural': 'ContactUs'},
        ),
    ]
