# Generated by Django 5.0 on 2023-12-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_productreview_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrderItems',
            new_name='CartOrderProducts',
        ),
    ]
