# Generated by Django 5.0 on 2023-12-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_address_mobile_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='review',
        ),
    ]
